files: ^blinky/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  -   id: check-yaml
      args: [--allow-multiple-documents]
      files: \.(yaml|yml)$
  -   id: end-of-file-fixer
      files: \.(yaml|yml|c|cpp|cc|cxx|h|hpp)$
  -   id: trailing-whitespace
      files: \.(yaml|yml|c|cpp|cc|cxx|h|hpp)$
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v21.1.8'
  hooks:
  -   id: clang-format
      files: \.(c|cpp|cc|cxx|h|hpp)$
- repo: https://github.com/cpplint/cpplint
  rev: '2.0.2'
  hooks:
  -   id: cpplint
      files: \.(c|cpp|cc|cxx|h|hpp)$
- repo: https://github.com/johnor/pre-commit-lizard
  rev: 'v1.17.10'
  hooks:
    - id: lizard-cpp
      name: lizard
      args: [-C 12]
      files: \.(c|cpp|cc|cxx|h|hpp)$
