# C++ support
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP17=y
# use zpp_lib
CONFIG_USE_ZPP_LIB=y

CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y

# CONFIG_KERNEL_LOG_LEVEL_DBG=y
# CONFIG_ZPP_RTOS_LOG_LEVEL_DBG=y
# CONFIG_ZPP_DRIVERS_LOG_LEVEL_DBG=y

CONFIG_SEGGER_SYSTEMVIEW_BOOT_ENABLE=y
CONFIG_SEGGER_SYSVIEW_POST_MORTEM_MODE=y

CONFIG_SPEED_OPTIMIZATIONS=y
