# C++ support
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP17=y
# use zpp_lib
CONFIG_USE_ZPP_LIB=y

# Logging disabled for performance
CONFIG_LOG=n
CONFIG_BOOT_BANNER=n

# Thread configuration
CONFIG_ZPP_THREAD_POOL_SIZE=8
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_TIMESLICING=n
CONFIG_THREAD_NAME=y

# SEGGER SystemView (for nRF board)
CONFIG_TRACING=y
CONFIG_SEGGER_SYSTEMVIEW=y
CONFIG_SEGGER_SYSTEMVIEW_BOOT_ENABLE=y
CONFIG_SEGGER_SYSVIEW_POST_MORTEM_MODE=n
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
