# C++ support
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP17=y
# use zpp_lib
CONFIG_USE_ZPP_LIB=y

# Activate logs
CONFIG_LOG=y
CONFIG_ASSERT=y
CONFIG_APP_LOG_LEVEL_DBG=y

# Activate user space
CONFIG_USERSPACE=y

# Debugger
CONFIG_SEGGER_SYSTEMVIEW_BOOT_ENABLE=y
CONFIG_SEGGER_SYSVIEW_POST_MORTEM_MODE=y


# Core dump
# CONFIG_DEBUG_COREDUMP=y
# CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y
